---
kind: pipeline
type: docker
name: default

steps:
- name: build
  image: golang:1.16
  commands:
  - sh scripts/build.sh

- name: publish
  image: plugins/docker:18
  settings:
    dockerfile: docker/Dockerfile.linux.amd64
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: dock.rythm.online/drone-vault
    registry: dock.rythm.online
    tags:
    - ${DRONE_COMMIT_SHA}
  when:
    branch:
    - rythm-deploy
    event:
    - push
    - tag
